package com.prac.s4.exception;

public class ExceptionMain2 {

	public static void main(String[] args) {
		int num1 =0;
		int num2 =0;
		try {
		int result = num2/num1;
		}catch(Exception exception) {
			exception.printStackTrace();
			System.out.println();
		}
	}

}
